site_name: E-TRAINEE Course at Heidelberg University (2026)
repo_url: https://github.com/3dgeo-heidelberg/etrainee_heidelberg_2026
docs_dir: ../course
site_dir: ../site

theme:
  logo: assets/img/logo_etrainee.svg
  favicon: assets/img/logo_etrainee.svg
  name: material
  custom_dir: overrides
  palette:
    primary: teal
    accent: indigo
  features:
    - search.highlight
    - content.code.copy
    - navigation.top
    - navigation.footer
use_directory_urls: false
plugins:
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
  - search
markdown_extensions:
  - attr_list
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/quiz_evaluation.js

nav:
- 'Home': 'index.md'
- 'Prerequisites': 'module0/module0.md'
- 'Module 1':
    - 'Overview': 'module1/module1.md'
    - 'Toolbox intro':
        - 'Toolbox overview': 'module1/toolbox_intro/ETRAINEE_intro_overview.md'
        - 'Visual Studio Code': 'module1/toolbox_intro/vscode.md'
        - 'Manage software packages and environments': 'module1/toolbox_intro/conda.md'
        - 'Jupyter Notebooks': 'module1/toolbox_intro/jupyter.ipynb'
        - 'Vector data with GeoPandas': 'module1/toolbox_intro/geopandas.ipynb'
        - 'Raster data with rasterio': 'module1/toolbox_intro/rasterio.ipynb'
        - 'Raster data with xarray': 'module1/toolbox_intro/xarray.ipynb'
    - 'Principles of remote sensing time series': 'module1/01_principles_of_remote_sensing_time_series/01_principles_of_remote_sensing_time_series.md'
    - 'Large time series datasets in remote sensing': 'module1/02_large_time_series_datasets_in_remote_sensing/02_large_time_series_datasets_in_remote_sensing.md'
    - 'Time series analysis based on classification': 'module1/03_time_series_analysis_based_on_classification/03_time_series_analysis_based_on_classification.md'
    - 'Trajectory-based analysis': 'module1/04_trajectory-based_analysis/04_trajectory_based_analysis.md'
    - 'Spatio-temporal data fusion': 'module1/05_spatio_temporal_data_fusion/05_spatio-temporal_data_fusion.md'
    - 'Reference data, validation and accuracy assessment': 'module1/06_reference_data_validation_accuracy_assessment/06_reference_data_validation_accuracy_assessment.md'
- 'Module 3':
    - 'Overview': 'module3/module3.md'
    - 'Principles of 3D/4D geographic point clouds' :
        - 'Lesson' : 'module3/01_pointcloud_principles/01_pointcloud_principles.md'
        - 'Exercise' : 'module3/01_pointcloud_principles/exercise/m3_theme1_exercise1.md'
    - 'Programming for point cloud analysis with Python' :
        - 'Lesson' : 'module3/02_pointcloud_programming_python/02_pointcloud_programming_python.ipynb'
        - 'Exercise' : 'module3/02_pointcloud_programming_python/exercise/m3_theme2_exercise1.ipynb'
    - 'Principles and basic algorithms of 3D change detection and analysis' :
        - 'Lesson' : 'module3/03_3d_change_analysis/03_3d_change_analysis.ipynb'
        - 'Exercise' : 'module3/03_3d_change_analysis/exercise/m3_theme3_exercise1.md'
    - 'Time series analysis of 3D point clouds' :
        - 'Lesson' : 'module3/04_3d_timeseries_analysis/04_3d_timeseries_analysis.ipynb'
        - 'Exercise' : 'module3/04_3d_timeseries_analysis/exercise/m3_theme4_exercise1.md'
    - 'Machine learning-based 3D/4D point cloud analysis' :
        - 'Lesson' : 'module3/05_pointcloud_machine_learning/05_pointcloud_machine_learning.ipynb'
        #- 'Exercise' : 'module3/05_pointcloud_machine_learning/exercise/m3_theme5_exercise1.md'
    - 'Case studies' :
        - 'Multitemporal 3D change analysis at an active rock glacier' : 'module3/06_casestudy_rockglacier/06_casestudy_rockglacier.ipynb'
        - 'Time series-based change analysis of sandy beach dynamics' : 'module3/06_casestudy_sandybeach/06_casestudy_sandybeach.ipynb'
- 'Software':
    - 'CloudCompare': 'software/software_cloudcompare.md'
    - 'EnMAP-Box': 'software/software_enmap_box.md'
    - 'Python': 'software/software_python.md'
    - 'QGIS': 'software/software_qgis.md'
    - 'R': 'software/software_r_language.md'
    - 'Google Earth Engine': 'software/software_gee.md'
- 'Use Cases and Data':
    - 'Data download': 'https://doi.org/10.5281/zenodo.10003574'
    - 'Multitemporal 3D point clouds of an active rock glacier' : 'data_usecases/usecase_rockglacier_ahk.md'
    - '4D point clouds of a sandy beach' : 'data_usecases/usecase_beach_kijkduin.md'
    - 'Vegetation disturbance detection in Polish-Slovak Tatra Mountains' : 'data_usecases/usecase_forests_tatras.md'
    - 'Land cover monitoring in Karkonosze/Krkonoše Mountains (Poland/Czechia)' : 'data_usecases/usecase_tundra_karkonosze.md'
    - 'Tundra vegetation monitoring in Krkonoše Mountains': 'data_usecases/usecase_grasses_krkonose.md'
    - 'Forest disturbances in Ore Mountains (Czechia)': 'data_usecases/usecase_ore_mts_disturbance.md'
- 'About the project': 'https://web.natur.cuni.cz/gis/etrainee/'
